[font]
normal.family = "Iosevka Fixed Curly"
normal.style = "Light Extended"
bold.style = "Bold Extended"
italic.style = "Extended Italic"
bold_italic.style = "Bold Extended Italic"
size = 14

[cursor]
style.shape = "Block"

[[hints.enabled]]
action = "Copy"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
]

[window]
dimensions = { columns = 200, lines = 50 }
padding = { x = 3, y = 3 }
position = { x = 100, y = 300 }
dynamic_title = false
title = ""
